---
- name: Publish a new version of the configured Content View
  hosts: tag_Name_satellite01
  connection: local

  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - foreman_admin_username is defined
          - foreman_admin_passwd is defined
          - foreman_organization is defined
          - foreman_content_view is defined
          - foreman_cv_end_date is defined

        fail_msg: "Required variables not set"

    - name: "Update the Content View Filter Rule"
      redhat.satellite.content_view_filter_rule:
        username: "{{ foreman_admin_username }}"
        password: "{{ foreman_admin_passwd }}"
        server_url: "https://{{ inventory_hostname }}"
        organization: "{{ foreman_organization }}"
        content_view: "{{ foreman_content_view }}"
        content_view_filter: "ErrataByDate"
        date_type: updated
        types:
          - bugfix
          - security
          - enhancement
        end_date: "{{ foreman_cv_end_date }}"
        validate_certs: false

    - name: "Publish the new version of Content View to Library"
      redhat.satellite.content_view_version:
        username: "{{ foreman_admin_username }}"
        password: "{{ foreman_admin_passwd }}"
        server_url: "https://{{ inventory_hostname }}"
        organization: "{{ foreman_organization }}"
        content_view: "{{ foreman_content_view }}"
        description: "Publishment-{{ foreman_cv_end_date }}"
        lifecycle_environments:
          - Library
        validate_certs: false
